[project]
name = "english-teacher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.31.0",
    "anthropic>=1.8.0",
    "apscheduler<4",
    "openai>=3.19.2",
    "pillow>=12.3.0",
    "pydantic-settings>=2.15.0",
]
